name: 01-building-blocks

on: workflow_dispatch

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello
              run: echo "Hello, World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: successful step
              run: |
                echo "This step will succeed"
                exit 0
            - name: Echo Goodbye
              run: echo "Goodbye, World!"